name: c1          # new env name
channels:
  - conda-forge                     # primary binary source
  - pytorch                         # official PyTorch wheels
dependencies:
  # ── core language ───────────────────────────────────────────────────
  - python=3.10                    # all libs below tested against 3.10
  - pip

  # ── numerics & science ──────────────────────────────────────────────
  - numpy=1.23
  - scipy=1.10
  - pandas=1.5
  - scikit-learn=1.3
  - sympy
  - numba
  - h5py
  - h5utils                        # quick HDF5 plotting
  - pygsl                          # special functions
  - qutip=4.7

  # ── plotting & notebooks ────────────────────────────────────────────
  - matplotlib=3.7
  - seaborn=0.13
  - jupyterlab=4.0
  - ipython
  - tqdm
  - pillow
  - ffmpeg                          # run-time codec
  - ffmpeg-python                   # convenience wrapper (via pip, see below)

  # ── photonics / EM solvers ──────────────────────────────────────────
  - meep=1.25                      # CPU build of pymeep
  - mpb=1.6
  - python-mpb=1.6
  - fenics                         # FEM package (brings dolfin)
  - pymeep=1.25

  # ── quantum / topology engines ──────────────────────────────────────
  - mpi4py                          # parallel QED & Floquet sweeps
  - openmpi                         # MPI implementation used by mpi4py

  # ── machine-learning stack ──────────────────────────────────────────
  - pytorch=2.0
  - cpuonly                         # comment-out & add `cudatoolkit=X.Y` for GPU
  - torchvision

  # ── testing & CI helpers ────────────────────────────────────────────
  - pytest
  - coverage

  # ── extra PyPI-only utilities ───────────────────────────────────────
  - pip:
      - ffmpeg-python              # kept here to mirror import style
      - meep-utilities             # small helper imported by `actual_meep_engine.py`
      - qutip-qip                  # quantum information processing tools
      - qutip-visualization         # visualization tools for QuTiP
      - qutip-qec                  # quantum error correction tools
      - qutip-qec-visualization     # visualization tools for QEC
      - qutip-qec-quantum-simulator # quantum simulator for QEC
      - qutip-qec-quantum-simulator-visualization # visualization tools for Q
